### ISSUE TITLE
PopPopupPageModel with object data - overload method

### ISSUE THREAD

**Issue by LeoJHarris** [libin85/FreshMvvm.Popup#1]
Hi there is it possible to add an overload on the PopPopupPageModel method to return data in the ReverseInit method of the returning PageModel. Same as like the PopPageModel method that takes object data.

Im in need of returning some data back to the page that pushed the popup page.

Thanks!

**Comment by LeoJHarris** [comment]
My apologies on appearing actually doesn't even get called when a popup page is popped, this might not be possible even with the overload. Perhaps due to a separate navigation stack.

**Comment by LeoJHarris** [comment]
Am just passing through the previous pagemodel and calling a function within that to handle the required data.

**Comment by mos379** [comment]
> Hi there is it possible to add an overload on the PopPopupPageModel method to return data in the ReverseInit method of the returning PageModel. Same as like the PopPageModel method that takes object data.
> 
> Im in need of returning some data back to the page that pushed the popup page.
> 
> Thanks!

How did you actually solve this? I would really like to keep the approach of using reverseinit...
